In [196]:
import numpy #for matrices
import scipy.special #for sigmoid
import random

In [197]:
class neuralNetwork:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learningrate
        
        #activation function, expit is sigmoid
        self.activation_function = lambda x: scipy.special.expit(x)
        
        #weights inside the arrays are w_i_j
        #where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc
        self.wih = numpy.random.normal(0.0,pow(self.hnodes, -0.5),(self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0,pow(self.onodes, -0.5),(self.onodes, self.hnodes))
        
        pass
    
    #train the neural net
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2s array
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        #input & hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        #hidden layer & output
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        #error is target-actual
        output_errors = targets - final_outputs
        
        #hidden error is the output errors, split by weights, recombinded at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors)
#         one = output_errors*final_outputs
#         two = numpy.dot(output_errors,final_outputs)
#         print(one)
#         print(two)
        #update weights between hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        #update weights between input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
       
        pass
    
    #query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2s array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        #input & hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        #hidden layer & output
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
    pass

In [198]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
learning_rate = 0.3

n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)


In [199]:
n.query([1.0,0.5,0.3])

array([[ 0.54983934],
       [ 0.53086211],
       [ 0.56618649]])

In [207]:
for i in range(100000):
    n.train([random.random(),random.random(),random.random()],[0.4,0.25,0.01])
    pass
n.query([random.random(),random.random(),random.random()])
    


array([[ 0.3979441 ],
       [ 0.25551395],
       [ 0.01059607]])

In [231]:
n.query([random.random(),random.random(),random.random()])

array([[ 0.40046787],
       [ 0.2459456 ],
       [ 0.00800258]])